language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm test
addons:
    code_climate:
        repo_token: 3d93025a8d5206336b3ce207227e67166871f65327b9926a23ccc6d662b824b5
after_success: npm run coverage